import {bookingDialog} from './booking-dialog.mjs';
import {mkdir,writeFile,cp,rm} from 'node:fs/promises';
import path from 'node:path';
import {prices,priceGroups,servicePriceIds,rubles} from './price-data.mjs';
import {anatomyPage,anatomyTeaser} from './tooth-page.mjs';
import {projectRoot,outputDir,basePath,withBasePath} from './site-config.mjs';
const out=outputDir;
// Fixed project-local output path; never delete a user-supplied directory.
if(path.resolve(out)!==path.resolve(projectRoot,'dist'))throw Error('Unsafe output directory');
await rm(out,{recursive:true,force:true});
await cp(path.join(projectRoot,'public'),out,{recursive:true});
await writeFile(path.join(out,'.nojekyll'),'');
await writeFile(path.join(out,'build-info.json'),JSON.stringify({basePath}));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const icon=(i)=>`<svg class="service-icon" viewBox="0 0 40 40" fill="none" stroke="currentColor" aria-hidden="true">${['<circle cx="17" cy="17" r="10"/><path d="m24 24 10 10M17 12v10m-5-5h10"/>','<path d="m20 4 3.5 11.5L35 19l-11.5 3.5L20 34l-3.5-11.5L5 19l11.5-3.5Z"/><path d="M33 3v8m-4-4h8"/>','<rect x="8" y="7" width="24" height="28" rx="7"/><path d="M20 13v15m-7-7.5h14"/>','<circle cx="20" cy="20" r="14"/><path d="M13 20h14M20 13v14"/>','<path d="M6 28h28M10 28V13q10-12 20 0v15M15 10v18m10-18v18M10 18h20"/>','<path d="M12 13V9q8-10 16 0v4ZM15 13l2 18 3 4 3-4 2-18M15 18h10m-9 5h8m-7 5h6"/>'][i]}</svg>`;
const services=[
{slug:'diagnostika',name:'Диагностика',desc:'Разобраться в состоянии зубов и понять, с чего начать.',category:'care'},
{slug:'gigiena',name:'Профессиональная гигиена',desc:'Профессиональная гигиена и удаление зубных отложений.',category:'care'},
{slug:'lechenie-zubov',name:'Лечение зубов',desc:'Пломбы из фотополимеров, реставрации и лечение корневых каналов.',category:'treatment'},
{slug:'udalenie-zubov',name:'Удаление зубов',desc:'Когда сохранить зуб нельзя — обсудить следующий шаг.',category:'treatment'},
{slug:'protezirovanie',name:'Протезирование',desc:'Коронки, вкладки, съёмные протезы и их восстановление.',category:'restore'},
{slug:'implantaciya',name:'Имплантация',desc:'Планирование восстановления и коронки с опорой на имплантаты.',category:'restore'}];
const nav=[['/services/','Услуги'],['/doctors/','Врачи'],['/about/','О клинике'],['/patients/','Пациентам'],['/prices/','Стоимость'],['/contacts/','Контакты'],['/tooth/','Структура зуба']];
const brand=`<a class="brand" href="/" aria-label="СМ-Стоматология — главная"><img class="brand-mark" src="/assets/logo-mark.svg" alt="" width="60" height="42"><span class="brand-name">СМ-СТОМАТОЛОГИЯ<span class="brand-sub">ЗАБОТА О ВАШЕЙ УЛЫБКЕ</span></span></a>`;
const appointment=(label='Записаться на приём',context='',cls='')=>`<button class="button ${cls}" data-appointment="${esc(context)}">${label}</button>`;
const footer=`<footer class="footer"><div class="container"><div class="footer-grid"><div>${brand}<p class="footer-address">Нижний Новгород,<br>ул. Березовская, д. 94, корп. 1, пом. 5</p></div><nav class="footer-nav" aria-label="Навигация в подвале">${nav.map(([href,name])=>`<a href="${href}">${name}</a>`).join('')}<a href="/journal/">Полезное</a><a href="/documents/">Документы</a></nav><div class="footer-contact"><a href="tel:+78312708220">+7 (831) 270-82-20</a><a href="tel:+79023040767">+7 (902) 304-07-67</a><small>Время работы уточняйте по телефону</small></div></div><div class="footer-bottom"><span>© 2026 СМ-Стоматология. Нижний Новгород.</span><a href="/privacy/">Конфиденциальность</a></div><div class="medical-notice">Имеются противопоказания. Необходима консультация специалиста.</div></div></footer>`;
const dialog=bookingDialog;
function layout(title,desc,body,url='/'){return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#a45135"><title>${esc(title)} | СМ-Стоматология</title><meta name="description" content="${esc(desc)}"><link rel="icon" type="image/svg+xml" href="/assets/logo-mark.svg"><link rel="stylesheet" href="/assets/style.css"><link rel="stylesheet" href="/assets/update.css"><link rel="stylesheet" href="/assets/booking.css"><script src="/assets/app.js" defer></script><script src="/assets/booking.js" defer></script><script src="/assets/update.js" defer></script></head><body><a class="skip-link" href="#main">Перейти к содержимому</a><div class="utility"><div class="container"><span>Нижний Новгород<span class="location-detail"> · ул. Березовская, 94, корп. 1</span></span><button class="text-button" data-reader aria-pressed="false">Увеличить текст</button></div></div><header class="header"><div class="container nav-row">${brand}<nav class="desktop-nav" id="main-nav" aria-label="Основная навигация">${nav.map(([href,name])=>`<a href="${href}"${url.startsWith(href)?' aria-current="page"':''}>${name}</a>`).join('')}</nav><div class="nav-cta">${appointment('Записаться','','small')}<button class="menu-toggle" aria-expanded="false" aria-controls="main-nav" aria-label="Открыть меню">☰</button></div></div></header><main id="main">${body}</main>${footer}<div class="mobile-call"><span>СМ-Стоматология<br>Нижний Новгород</span>${appointment('Записаться','','small')}</div>${dialog}</body></html>`}
const serviceCards=()=>services.map((s,i)=>`<a class="service-card" href="/services/${s.slug}/" data-service-card data-category="${s.category}"><div class="card-top">${icon(i)}<span class="card-number">0${i+1}</span></div><h3>${s.name}</h3><p>${s.desc}</p><span class="card-link">Об услуге</span></a>`).join('');
const articles=[{slug:'daily-care',tag:'Ежедневный уход · 2 минуты',title:'Здоровая улыбка начинается дома',num:'2×',caption:'в день — время для себя'},{slug:'first-visit',tag:'Первый визит · 3 минуты',title:'На приём спокойно и без лишних вопросов',num:'01',caption:'визит, с которого всё начинается'},{slug:'treatment-plan',tag:'План лечения · 3 минуты',title:'Что спросить у врача до начала лечения',num:'5',caption:'вопросов, которые стоит задать'}];
const journalCards=()=>articles.map(a=>`<a class="journal-card" href="/journal/${a.slug}/"><div class="journal-art"><strong>${a.num}</strong><span>${a.caption}</span></div><div class="journal-body"><small>${a.tag}</small><h3>${a.title}</h3><span class="card-link">Читать памятку</span></div></a>`).join('');
const faqs=[['Я не знаю, какая услуга мне нужна. С чего начать?','Начните с консультации. При записи достаточно рассказать, что вас беспокоит. После осмотра врач сможет обсудить подходящие варианты и необходимость дополнительных исследований.'],['Можно ли узнать стоимость до лечения?','Спросите о стоимости консультации при записи. Полный объём лечения и итоговая сумма зависят от осмотра, материалов и необходимых этапов. Попросите врача объяснить план и стоимость каждого этапа до начала лечения.'],['Что делать, если я боюсь стоматолога?','Скажите об этом администратору и врачу. Расскажите, что именно тревожит, попросите объяснять действия заранее и договоритесь о сигнале для паузы.'],['Как записаться на приём?','Позвоните по номеру +7 (831) 270-82-20 или +7 (902) 304-07-67. Администратор поможет выбрать время и уточнит, что взять с собой.']];
const faqList=(items=faqs)=>items.map(([q,a])=>`<details><summary>${q}</summary><div><p>${a}</p></div></details>`).join('');
const contactBand=()=>`<div class="container"><section class="contact-band"><div><h2>Начнём с простого.<br>С разговора о вашей улыбке.</h2><p>Расскажите, что вас беспокоит. Следующий шаг обсудим вместе.</p></div>${appointment('Выбрать время')}</section></div>`;
const home=`<div class="container"><section class="hero"><div class="hero-copy"><div class="eyebrow">Стоматология в Нижнем Новгороде</div><h1>Больше поводов<br>улыбаться.<em>Меньше тревог.</em></h1><p class="hero-description">От первого вопроса до плана лечения.<br>СМ-Стоматология на Березовской —<br>место, где начинается забота о вашей улыбке.</p><div class="hero-actions">${appointment()}<a class="button outline" href="/services/">Подобрать услугу</a></div><div class="hero-bottom"><span class="mini-plus" aria-hidden="true">+</span><span>Не знаете, с чего начать?<br>Начните со знакомства с врачом.</span></div></div><div class="hero-visual"><img src="/assets/visit.jpg" alt="Консультация в стоматологическом кабинете" width="1920" height="616" fetchpriority="high"><span class="hero-tag">С заботой о вас</span><div class="image-note"><div><strong>Ваша улыбка. Ваш темп.</strong><small>Разобраться, обсудить, принять решение.</small></div><span class="round-symbol" aria-hidden="true">✳</span></div></div></section><div class="value-strip"><div class="value-item"><span>01 /</span> От профилактики до восстановления</div><div class="value-item"><span>02 /</span> Понятно о каждом этапе</div><div class="value-item"><span>03 /</span> Рядом — на Березовской</div></div><section class="section reveal"><div class="section-top"><div><div class="eyebrow">Забота в деталях</div><h2>Что нужно вашей улыбке?</h2></div><a class="text-link" href="/services/">Все направления</a></div><div class="services-grid">${serviceCards()}</div></section><section class="dark-section reveal"><div><div class="eyebrow">Первый визит</div><h2>Когда всё понятно,<br>намного спокойнее.</h2><p>Приём начинается с ваших вопросов. Вот что обычно помогает перейти от волнения к понятному плану.</p><a class="button light" href="/patients/">Подготовиться к приёму</a></div><ol class="steps"><li><h3>Расскажите о себе</h3><p>Что беспокоит, какой результат важен и что вызывает тревогу.</p></li><li><h3>Узнайте, что происходит</h3><p>Осмотр и обсуждение того, нужны ли дополнительные исследования.</p></li><li><h3>Обсудите следующий шаг</h3><p>Варианты лечения, этапы, сроки и стоимость — до принятия решения.</p></li></ol></section><section class="section reveal"><div class="section-top"><div><div class="eyebrow">Полезно знать</div><h2>Маленькие привычки.<br>Большая забота.</h2></div><a class="text-link" href="/journal/">Все памятки</a></div><div class="journal-grid">${journalCards()}</div></section>${anatomyTeaser}<section class="section faq-grid reveal"><div><div class="eyebrow">Открытый разговор</div><h2>Возможно, вы<br>хотели спросить</h2><p>Собрали то, что часто волнует перед приёмом.</p></div><div>${faqList()}</div></section></div>${contactBand()}`;
async function page(url,title,desc,body){const dest=url==='/'?'index.html':url==='404'?'404.html':url.replace(/^\//,'')+'index.html';await mkdir(path.dirname(path.join(out,dest)),{recursive:true});await writeFile(path.join(out,dest),withBasePath(layout(title,desc,body,url)));}
await page('/','Стоматология в Нижнем Новгороде','СМ-Стоматология на Березовской: диагностика, гигиена, лечение, протезирование и имплантация. Услуги, памятки пациентам и запись по телефону.',home);
// Additional page content is defined below.
const intro=(title,subtitle,eyebrow='СМ-Стоматология')=>`<div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${subtitle}</p>`;
const crumb=(name)=>`<nav class="breadcrumb" aria-label="Хлебные крошки"><a href="/">Главная</a><span aria-hidden="true">/</span><span>${name}</span></nav>`;
const pageBody=(title,subtitle,body,eyebrow='СМ-Стоматология',cta=true)=>`<div class="container">${crumb(title.replaceAll('<br>',' '))}<section class="page-intro">${intro(title,subtitle,eyebrow)}</section><div class="page-content">${body}</div></div>${cta?contactBand():''}`;
const aside=(title='Остались вопросы?',text='Обсудите их с администратором и врачом. Позвоните, чтобы выбрать удобное время для консультации.',context='')=>`<aside class="aside-card"><div class="eyebrow">Следующий шаг</div><h3>${title}</h3><p>${text}</p>${appointment('Записаться',context)}<small>+7 (831) 270-82-20<br>Нижний Новгород, Березовская, 94, корп. 1</small></aside>`;
const sources=(items)=>`<div class="sources">Материалы для дополнительного чтения:${items.map(([label,href])=>`<a href="${href}" target="_blank" rel="noopener noreferrer">${label} (на английском)</a>`).join('')}</div>`;
const visitSource=['NHS — что происходит на приёме у стоматолога','https://www.nhs.uk/nhs-services/dentists/what-happens-when-you-visit-the-dentist/'];
const careSource=['NHS — как правильно очищать зубы','https://www.nhs.uk/live-well/healthy-teeth-and-gums/how-to-keep-your-teeth-clean/'];
const checksSource=['NHS — профилактические осмотры','https://www.nhs.uk/live-well/healthy-teeth-and-gums/dental-check-ups/'];
await page('/services/','Услуги','Шесть направлений СМ-Стоматологии: найдите нужную услугу и узнайте, что обсудить на консультации.',pageBody('Забота, которая<br>начинается с вас.','Выберите направление или найдите интересующую услугу. Если не знаете, что нужно, начните с консультации.',`<label class="search-label" for="service-search">Какая услуга вас интересует?</label><input class="search-field" id="service-search" data-service-search type="search" placeholder="Например, гигиена или имплантация"><div class="filter-bar" role="group" aria-label="Направления услуг"><button class="filter-button" data-filter="all" aria-pressed="true">Все услуги</button><button class="filter-button" data-filter="care" aria-pressed="false">Профилактика</button><button class="filter-button" data-filter="treatment" aria-pressed="false">Лечение</button><button class="filter-button" data-filter="restore" aria-pressed="false">Восстановление</button></div><p class="small-note" data-search-status role="status">Направлений: 6</p><div class="services-grid">${serviceCards()}</div><div class="empty-state" data-empty hidden><h3>Такую услугу не нашли</h3><p>Попробуйте другое название или откройте все направления.</p><button class="button outline" data-reset-search>Сбросить поиск</button></div><div class="callout">Название услуги не заменяет диагноз. Подходящий вариант лечения врач определяет после осмотра и обсуждения вашей ситуации.</div>`,'Услуги клиники'));
const serviceContent=[
{lead:'Сначала разобраться.<br>Потом действовать.',about:'Консультация помогает обсудить жалобы, оценить состояние полости рта и понять, нужны ли дополнительные исследования. Это отправная точка для дальнейших решений.',situations:['Вы давно не были на профилактическом осмотре.','Есть вопросы о состоянии зубов, дёсен или старых реставраций.','Вы хотите обсудить варианты восстановления зубов.'],steps:['Расскажите о жалобах, прошлом лечении и принимаемых лекарствах.','Врач проведёт осмотр и обсудит необходимость исследований.','Уточните выводы, возможные варианты и последовательность дальнейших действий.'],questions:['Какие исследования нужны именно в моей ситуации?','Что можно понять по осмотру, а что требует уточнения?','Когда мне прийти на следующий профилактический осмотр?'],faq:[['Нужны ли снимки всем пациентам?','Необходимость и вид исследования определяет врач. Не стоит проходить исследования заранее без назначения: сначала уточните, что требуется.'],['Как часто проходить осмотр?','Интервал зависит от состояния зубов и дёсен и индивидуальных факторов риска. Согласуйте срок следующего осмотра с врачом.']],source:[checksSource]},
{lead:'Ежедневная забота.<br>Профессиональная поддержка.',about:'На консультации по гигиене можно обсудить профессиональное очищение зубов и домашний уход: щётку, пасту и очищение межзубных промежутков. Подходящий объём процедуры определяет специалист.',situations:['Вы хотите обсудить профилактический уход.','Замечаете налёт или участки, которые сложно очищать дома.','Нужны рекомендации по уходу за реставрациями и ортопедическими конструкциями.'],steps:['Обсудите состояние зубов и дёсен и особенности домашнего ухода.','Уточните, какие методы очищения предложены и почему.','Попросите показать технику ухода и подобрать средства для дома.'],questions:['Как очищать труднодоступные участки?','Подходит ли мне зубная нить или межзубные ёршики?','Какие рекомендации соблюдать после процедуры?'],faq:[['Заменяет ли гигиена ежедневную чистку?','Нет. Домашний уход остаётся необходимым. Профессиональная процедура и ежедневное очищение решают разные задачи.'],['Что делать, если дёсны кровоточат?','Расскажите об этом стоматологу. Кровоточивость — повод проверить состояние дёсен, а не просто сменить пасту.']],source:[careSource,['NHS — заболевания дёсен','https://www.nhs.uk/conditions/gum-disease/']]},
{lead:'Сохранить своё.<br>Обсудить возможности.',about:'Лечение начинается с понимания причины жалоб. После осмотра врач обсуждает с вами, какие ткани требуют лечения, как можно восстановить зуб и что входит в предложенный план.',situations:['Зуб беспокоит или реагирует на раздражители.','Повредилась пломба или появился скол.','Вы хотите проверить ранее леченный зуб.'],steps:['Опишите, когда появилась проблема и что вызывает дискомфорт.','Обсудите диагноз, варианты лечения и их ограничения.','Уточните стоимость, число визитов и рекомендации после лечения.'],questions:['Можно ли сохранить зуб и какие есть варианты?','Почему предлагается именно такой способ восстановления?','Что делать, если после лечения появится дискомфорт?'],faq:[['Можно ли выбрать лечение по описанию симптомов?','По одному описанию нельзя надёжно определить причину. Нужны осмотр и, при необходимости, дополнительные исследования.'],['Будет ли лечение выполнено за один визит?','Количество посещений зависит от диагноза и объёма работы. Точный план обсудите с врачом после осмотра.']],source:[]},
{lead:'Взвешенное решение.<br>Понятный следующий шаг.',about:'Если обсуждается удаление, важно понять его причину, возможные альтернативы и дальнейший план. Все вопросы о подготовке и восстановлении задайте врачу до вмешательства.',situations:['Врач предложил обсудить удаление зуба.','Есть вопросы о проблемном зубе мудрости.','Нужен план действий перед последующим восстановлением зубного ряда.'],steps:['Обсудите, почему предлагается удаление и можно ли сохранить зуб.','Сообщите врачу о заболеваниях, аллергиях и всех принимаемых лекарствах.','Получите персональные инструкции по подготовке и уходу после вмешательства.'],questions:['Какие есть альтернативы удалению?','Что мне нужно знать о подготовке?','Как связаться с клиникой при вопросах после процедуры?'],faq:[['Нужно ли отменять лекарства перед удалением?','Самостоятельно не отменяйте и не меняйте назначенные препараты. Обсудите их список с врачом заранее.'],['Можно ли получить универсальную памятку по восстановлению?','Рекомендации зависят от вмешательства и вашей ситуации. Попросите врача выдать персональную памятку и объяснить, в каких случаях нужно связаться с клиникой.']],source:[]},
{lead:'Комфорт в деталях.<br>Улыбка в привычной жизни.',about:'На консультации по протезированию обсуждают восстановление повреждённых или отсутствующих зубов. Выбор конструкции зависит от состояния полости рта, задач лечения и предпочтений пациента.',situations:['Нужно обсудить восстановление сильно повреждённого зуба.','Отсутствует один или несколько зубов.','Вы хотите оценить состояние существующей конструкции.'],steps:['Расскажите, что важно для вас: внешний вид, комфорт, привычки.','Сравните предложенные варианты, особенности ухода и ограничения.','Уточните подготовку, примерки, стоимость и план наблюдения.'],questions:['Какие конструкции подходят в моей ситуации?','Что входит в полную стоимость восстановления?','Как ухаживать за конструкцией и когда приходить на контроль?'],faq:[['Можно ли выбрать конструкцию только по фотографии?','Фотография может помочь объяснить эстетические пожелания, но выбор конструкции требует оценки состояния полости рта.'],['Из чего складывается стоимость?','Обсудите отдельно подготовку, конструкцию, примерки и сопутствующие этапы. Попросите перечислить всё, что входит в предложенную сумму.']],source:[]},
{lead:'Восстановление зубов.<br>С вниманием к плану.',about:'Консультация по имплантации — возможность обсудить один из способов восстановления отсутствующих зубов. Подходит ли этот вариант, врач определяет после обследования и оценки вашего здоровья.',situations:['Вы хотите узнать о восстановлении отсутствующего зуба.','Сравниваете имплантацию с другими вариантами.','Нужен подробный план этапов и расходов.'],steps:['Обсудите состояние здоровья и необходимые обследования.','Уточните возможные варианты восстановления и последовательность этапов.','Попросите отдельный расчёт хирургической и ортопедической частей лечения.'],questions:['Подходит ли мне этот метод и какие есть альтернативы?','Нужна ли дополнительная подготовка?','Какие этапы входят в стоимость, а какие рассчитываются отдельно?'],faq:[['Всем ли подходит имплантация?','Возможность лечения оценивается индивидуально. Решение нельзя принять только по желанию пациента или фотографии.'],['Что означает «под ключ»?','Состав такого предложения может отличаться. Уточните, включены ли обследования, подготовка, имплант, ортопедическая конструкция и последующие посещения.']],source:[]}
];
const serviceExcerpts={
diagnostika:'В прейскуранте отдельно указаны первичная консультация, прицельная внутриротовая рентгенография и радиовизиография. Исследования назначаются по показаниям.',
gigiena:'Прейскурант включает профессиональную гигиену полости рта и зубов, ручное и ультразвуковое удаление наддесневых и поддесневых отложений. Для отдельных процедур цена указана за область одного зуба.',
'lechenie-zubov':'В клинике предусмотрены восстановление зуба пломбой из фотополимеров, обработка и пломбирование корневых каналов. Стоимость зависит от выбранных этапов, материала и количества каналов.',
protezirovanie:'В прейскуранте представлены литые, металлокерамические и пластмассовые коронки, культевые вкладки, съёмные протезы, починка и перебазировка конструкций.',
implantaciya:'Ортопедический прейскурант содержит коронки с опорой на имплантаты HI-TEC, ANY-RIDGE и NOBEL Biocare, с цементной и винтовой фиксацией. Цены ниже относятся к коронкам с цементной фиксацией; операция установки имплантата в них не включена.'};
const excerptRows=slug=>(servicePriceIds[slug]||[]).map(id=>prices.find(p=>p.id===id));
const serviceExcerpt=slug=>serviceExcerpts[slug]?`<section class="service-prices"><div class="eyebrow">Из прейскуранта клиники</div><h2>Услуги и стоимость</h2><p>${serviceExcerpts[slug]}</p>${excerptRows(slug).map(p=>`<div class="excerpt-row"><div><h3>${p.name}</h3><small>${p.note}</small></div><strong>${rubles(p.amount)}</strong></div>`).join('')}<p class="small-note">Указаны отдельные позиции, а не полная стоимость лечения. Состав плана и дополнительные этапы согласуются с врачом.</p><a class="text-link" href="/prices/">Посмотреть оба прейскуранта</a></section>`:'';
for(const [i,s]of services.entries()){const c=serviceContent[i];await page(`/services/${s.slug}/`,s.name,`${s.name} в СМ-Стоматологии: что обсудить с врачом, как подготовиться и какие вопросы задать.`,pageBody(c.lead,c.about,`<div class="split"><article class="article">${serviceExcerpt(s.slug)}<h2>Когда стоит обсудить с врачом</h2><ul>${c.situations.map(t=>`<li>${t}</li>`).join('')}</ul><h2>Как подойти к решению</h2><ol>${c.steps.map(t=>`<li>${t}</li>`).join('')}</ol><div class="callout">${i===0?'Профилактические осмотры помогают вовремя заметить изменения. Если появились жалобы, не ждите планового визита.':'Информация помогает подготовиться к разговору. Диагноз, показания и план лечения определяются на очной консультации.'}</div><h2>Три вопроса на консультации</h2><ul>${c.questions.map(t=>`<li>${t}</li>`).join('')}</ul><h2>Частые вопросы</h2>${faqList(c.faq)}${c.source.length?sources(c.source):''}<p style="margin-top:30px"><a class="text-link" href="/services/">Вернуться ко всем услугам</a></p></article>${aside('Обсудим вашу ситуацию','В прейскурантах указаны отдельные позиции. Полный план и итоговая стоимость определяются после осмотра.',s.name)}</div>`,s.name));}
const doctorData=[['Смирнов','Игорь Вячеславович','smirnov'],['Галактионова','Марина Николаевна','galaktionova'],['Симанская','Марина Александровна','simanskaya']];
await page('/doctors/','Врачи клиники','Специалисты СМ-Стоматологии. Уточните направление приёма и расписание у администратора.',pageBody('Знакомство<br>начинается с доверия.','Вы можете записаться к конкретному специалисту или попросить администратора помочь с выбором по вашему вопросу.',`<div class="card-grid">${doctorData.map(([surname,name,photo])=>`<section class="info-card doctor-card"><div class="doctor-portrait"><img src="/assets/doctor-${photo}.jpg" alt="${surname} ${name}" width="300" height="300" loading="lazy"></div><h3>${surname}<span>${name}</span></h3><p>Направление и ближайшее время приёма уточняйте у администратора.</p>${appointment('Уточнить приём',`${surname} ${name}`,'outline small')}</section>`).join('')}</div><section class="section"><div class="section-top"><h2>Ваши вопросы важны</h2><p>Выбирая врача, обсудите то, что поможет чувствовать себя увереннее.</p></div><div class="card-grid"><div class="info-card"><span class="label">01 / ЗАДАЧА</span><h3>Ваш повод обращения</h3><p>Опишите, что беспокоит и какой результат хотите получить. Это поможет выбрать нужное направление приёма.</p></div><div class="info-card"><span class="label">02 / ПОДХОД</span><h3>Ваш комфорт</h3><p>Расскажите о тревоге, предыдущем опыте и особенностях здоровья, которые нужно учитывать.</p></div><div class="info-card"><span class="label">03 / РЕШЕНИЕ</span><h3>Ваш план</h3><p>Попросите объяснить варианты, ожидаемые этапы, ограничения и стоимость до начала лечения.</p></div></div></section>`,'Специалисты'));
await page('/about/','О клинике','СМ-Стоматология в Нижнем Новгороде на улице Березовской. Направления помощи, подготовка к визиту и контакты.',pageBody('Здесь начинается<br>забота о вашей улыбке.','СМ-Стоматология — клиника на Березовской в Нижнем Новгороде. От вопросов о ежедневном уходе до обсуждения восстановления зубов.',`<img class="about-image" src="/assets/smile.jpg" alt="Пациентка смотрит на улыбку в зеркало" width="1920" height="616"><section class="section"><div class="section-top"><h2>Разобраться.<br>Обсудить. Решить.</h2><p>Важное в лечении — не только результат, но и понимание того, как к нему прийти.</p></div><div class="card-grid"><div class="info-card"><span class="label">ПРОФИЛАКТИКА</span><h3>Забота каждый день</h3><p>Осмотр и профессиональная гигиена дополняют домашний уход. Обсудите с врачом, что подходит именно вам.</p><a class="text-link" href="/services/gigiena/">О гигиене</a></div><div class="info-card"><span class="label">ЛЕЧЕНИЕ</span><h3>Внимание к причине</h3><p>Диагностика помогает перейти от описания жалоб к обсуждению возможных вариантов лечения.</p><a class="text-link" href="/services/lechenie-zubov/">О лечении зубов</a></div><div class="info-card"><span class="label">ВОССТАНОВЛЕНИЕ</span><h3>Комфорт и улыбка</h3><p>Протезирование и имплантация — направления, о которых можно узнать на консультации.</p><a class="text-link" href="/services/protezirovanie/">О протезировании</a></div></div></section><section class="dark-section"><div><div class="eyebrow">Рядом с вами</div><h2>Нижний Новгород.<br>Березовская, 94.</h2><p>Корпус 1, помещение 5.<br>Перед визитом уточните время приёма по телефону.</p><a class="button light" href="/contacts/">Как добраться</a></div><div><h3 style="margin-bottom:25px">Больше информации о клинике</h3><p>Сведения о специалистах, документы и условия приёма помогают подготовиться к визиту.</p><p><a class="text-link" href="/doctors/">Специалисты клиники</a></p><p><a class="text-link" href="/documents/">Документы и сведения</a></p><p><a class="text-link" href="/patients/">Информация пациентам</a></p></div></section>`,'О клинике'));
const checks=['Уточнить дату, время и стоимость консультации.','Подготовить документ, удостоверяющий личность.','Составить список принимаемых лекарств и известных аллергий.','Взять имеющиеся снимки и заключения по вашему вопросу.','Записать жалобы и вопросы, которые хотите обсудить.'];
const checklist=()=>`<section class="checklist" data-checklist><div class="eyebrow">Небольшая подготовка</div><h3>Ваш список перед визитом</h3><p class="small-note">Отмечайте готовое. Отметки действуют, пока открыта страница.</p>${checks.map((s,i)=>`<label><input type="checkbox" name="visit-${i}"><span>${s}</span></label>`).join('')}<div class="progress-track" aria-hidden="true"><div class="progress-fill"></div></div><div class="check-status" role="status" aria-live="polite">Готово 0 из 5</div><div class="check-actions"><button data-reset-checks>Начать заново</button><button data-print>Распечатать</button></div></section>`;
await page('/patients/','Пациентам','Подготовка к первому приёму: интерактивный список, этапы визита и ответы на частые вопросы.',pageBody('Меньше неизвестности.<br>Больше спокойствия.','Собрали самое нужное перед посещением стоматолога. Сохраните вопросы, подготовьте документы и дайте себе время на знакомство с врачом.',`<div class="split"><div>${checklist()}</div>${aside('Первый раз в клинике?','Для записи не обязательно знать название процедуры. Расскажите администратору, с каким вопросом хотите обратиться.','Первичный приём')}</div><section class="section"><div class="section-top"><h2>Ваш визит —<br>шаг за шагом</h2></div><div class="timeline-light"><div><strong>01 / ЗАПИСЬ</strong><h3>Выбираем время</h3><p>Позвоните и уточните специалиста, стоимость консультации и время приёма.</p></div><div><strong>02 / ЗНАКОМСТВО</strong><h3>Говорим о важном</h3><p>Расскажите врачу о жалобах, лекарствах, особенностях здоровья и тревогах.</p></div><div><strong>03 / ОСМОТР</strong><h3>Разбираемся</h3><p>Врач осматривает полость рта и обсуждает необходимость исследований.</p></div><div><strong>04 / ПЛАН</strong><h3>Обсуждаем варианты</h3><p>Уточните этапы, стоимость и следующие действия. Задавайте вопросы.</p></div></div></section><div class="faq-grid"><div><h2>О чём можно<br>спросить заранее</h2><p style="margin-top:20px">Звонок в клинику поможет подготовиться к приёму.</p></div><div>${faqList([...faqs,['Как перенести запись?','Позвоните в клинику как можно раньше. Администратор поможет согласовать другое время.'],['Принимаете ли вы детей?','Возможность приёма ребёнка и подходящего специалиста уточните у администратора до записи.']])}</div></div>${sources([visitSource])}`,'Перед приёмом'));
const downloads=`<div class="download-grid"><a class="download-card" href="/documents/therapy-price.docx" download><span class="download-type">DOCX / ПРЕЙСКУРАНТ</span><h3>Терапия и профилактика</h3><span>Скачать полный документ · 30 КБ</span></a><a class="download-card" href="/documents/orthopedic-price.docx" download><span class="download-type">DOCX / ПРЕЙСКУРАНТ</span><h3>Ортопедическая стоматология</h3><span>Скачать полный документ · 32 КБ</span></a></div>`;
await page('/prices/','Цены и прейскуранты','Цены на консультации, гигиену, лечение зубов, коронки и протезирование. Два полных прейскуранта СМ-Стоматологии для скачивания.',pageBody('Стоимость.<br>Всё по порядку.','Основные позиции из прейскурантов клиники. Цена отдельной процедуры не равна полной стоимости лечения: необходимые этапы согласуются после осмотра.',`${downloads}<section class="price-catalog"><div class="section-top"><h2>Найдите нужную услугу</h2><p>Терапия, профилактика и ортопедия в одном списке.</p></div><label for="price-search" class="search-label">Название услуги, материал или код</label><input type="search" id="price-search" class="search-field" placeholder="Например, коронка или гигиена" data-price-search><div class="filter-bar" role="group" aria-label="Разделы прейскуранта"><button class="filter-button" data-price-filter="all" aria-pressed="true">Все</button>${Object.entries(priceGroups).map(([key,label])=>`<button class="filter-button" data-price-filter="${key}" aria-pressed="false">${label}</button>`).join('')}</div><p class="small-note" data-price-status role="status">Позиций: ${prices.length}</p><div class="price-list">${prices.map(p=>`<div class="catalog-row" data-price-row data-group="${p.group}"><div><span class="price-category">${priceGroups[p.group]}</span><h3>${p.name}</h3><p>${p.note}</p><small>${p.code?`Код ${p.code} · `:''}${p.source==='therapy'?'Терапевтический':'Ортопедический'} прейскурант</small></div><strong>${rubles(p.amount)}</strong></div>`).join('')}</div><div class="empty-state" data-price-empty hidden><h3>Таких позиций не найдено</h3><p>Измените запрос или откройте полные документы выше.</p><button class="button outline" data-price-reset>Сбросить поиск</button></div><div class="callout">В полных документах есть дополнительные позиции и варианты материалов. Если стоимость не указана или требуется уточнение, обратитесь к администратору. Цены на установку имплантатов и удаление зубов в этих двух прейскурантах не приведены.</div><p class="small-note">Даты введения тарифов в переданных документах не указаны. Действующую стоимость подтвердите при записи.</p></section>`,'Прейскуранты клиники'));
await page('/journal/','Полезное пациентам','Короткие памятки о домашнем уходе, первом визите и вопросах перед лечением.',pageBody('Знать больше.<br>Заботиться проще.','Короткие памятки о привычках, подготовке к приёму и осознанных решениях. Без сложных терминов.',`<div class="journal-grid">${journalCards()}</div>${anatomyTeaser}<div class="callout">Материалы носят общий информационный характер. Персональные рекомендации даст врач с учётом вашего состояния здоровья.</div>`,'Журнал заботы'));
const articleBodies=[
`<h2>Две минуты утром и вечером</h2><p>Чистите зубы фторсодержащей пастой дважды в день примерно по две минуты. Один из этих разов — перед сном. Уделяйте внимание наружной, внутренней и жевательной поверхностям.</p><h2>Не только щётка</h2><p>Для очищения между зубами используют нить или межзубные ёршики. Стоматолог поможет подобрать подходящее средство и покажет технику.</p><h2>После чистки</h2><p>Сплюньте избыток пасты, но не полощите рот водой сразу: она смывает оставшийся фтор. Ополаскиватель, если вы им пользуетесь, лучше применять в другое время.</p><h2>Ручная или электрическая?</h2><p>Оба варианта могут хорошо очищать зубы. Важнее тщательно проходить все поверхности и пользоваться подходящей пастой. Если чистить неудобно, обсудите выбор щётки со специалистом.</p><div class="callout">Домашний уход дополняет, но не заменяет осмотр. Срок следующего профилактического визита подбирается индивидуально.</div>${sources([careSource,checksSource])}`,
`<h2>Не нужно знать всё заранее</h2><p>При записи достаточно рассказать, что вас беспокоит. Запишите, когда появился дискомфорт, что вы замечаете и какие вопросы хотите задать. Это поможет не забыть важное во время разговора.</p><h2>Возьмите информацию о здоровье</h2><p>Подготовьте список лекарств, которые принимаете, и известных аллергий. Если у вас есть снимки и заключения по вопросу обращения, уточните в клинике, как лучше их предоставить.</p><h2>Если вы волнуетесь</h2><p>Расскажите врачу, чего именно боитесь. Попросите объяснять действия и договоритесь о сигнале для остановки. Во время осмотра можно попросить паузу.</p><h2>Перед уходом</h2><p>Уточните, что выяснилось, какие варианты предлагаются и что делать дальше. Если что-то осталось непонятным, попросите объяснить другими словами.</p><div class="callout">Не отменяйте назначенные лекарства самостоятельно. Вопросы подготовки обсудите с врачом.</div><p><a class="button outline" href="/patients/">Открыть список подготовки</a></p>${sources([visitSource])}`,
`<h2>01. Какую задачу мы решаем?</h2><p>Попросите объяснить диагноз и цель каждого предложенного этапа. Полезно понимать, что требует внимания сейчас, а что обсуждается отдельно.</p><h2>02. Какие есть варианты?</h2><p>Спросите об альтернативных подходах, их преимуществах и ограничениях. Выбор легче сделать, когда сравниваются не только цены.</p><h2>03. Что входит в стоимость?</h2><p>Уточните обследования, подготовку, материалы и контрольные посещения. Попросите перечислить этапы и условия изменения расчёта.</p><h2>04. Как будет организовано лечение?</h2><p>Обсудите предполагаемое число посещений, промежутки между ними и то, что может изменить сроки. Так проще совместить лечение с работой и другими делами.</p><h2>05. Что потребуется от меня?</h2><p>Узнайте о домашнем уходе, ограничениях после процедуры и способе связи с клиникой. Сохраните персональные рекомендации, выданные врачом.</p><div class="callout">Вопросы не мешают лечению. Они помогают понять предложенный план и участвовать в решении.</div><p><a class="button outline" href="/prices/">Как уточнить стоимость</a></p>`
];
for(const [i,a]of articles.entries())await page(`/journal/${a.slug}/`,a.title,a.title+'. Памятка пациенту СМ-Стоматологии.',pageBody(a.title,'Небольшая памятка, к которой удобно вернуться перед визитом или в повседневной жизни.',`<div class="split"><article class="article">${articleBodies[i]}<p style="margin-top:35px"><a class="text-link" href="/journal/">Все памятки</a></p></article>${aside('Обсудите с врачом','Общие советы не учитывают все особенности здоровья. Персональные рекомендации можно получить на консультации.')}</div>`,a.tag));
const mapQuery=encodeURIComponent('Нижний Новгород, Березовская улица, 94к1');
await page('/contacts/','Контакты','Адрес и телефоны СМ-Стоматологии: Нижний Новгород, ул. Березовская, д. 94, корп. 1, пом. 5.',pageBody('Будем рады<br>знакомству.', 'Позвоните, чтобы задать вопрос, выбрать специалиста или согласовать время приёма.',`<div class="contact-grid"><section class="address-card"><div class="eyebrow">СМ-Стоматология</div><h2>Нижний Новгород,<br>Березовская, 94</h2><p>Корпус 1, помещение 5</p><a class="phone-large" href="tel:+78312708220">+7 (831) 270-82-20</a><a class="phone-large" href="tel:+79023040767">+7 (902) 304-07-67</a><p style="margin-top:27px">Время работы и ближайшие свободные<br>часы приёма уточняйте по телефону.</p><a class="text-link" href="mailto:info@sm-stomatolog.ru">info@sm-stomatolog.ru</a></section><section class="route-card map-card"><iframe title="Яндекс Карта: СМ Стоматология, Берёзовская, 94, корпус 1" src="https://yandex.ru/map-widget/v1/?ol=biz&amp;oid=45158356463&amp;z=16" width="640" height="400" loading="lazy" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe><div class="map-caption"><div><div class="eyebrow">Планируем визит</div><h3>Мы уже на карте</h3><p>На карте отмечена СМ-Стоматология на Берёзовской, 94, корпус 1. Откройте маршрут или уточните расположение входа у администратора.</p></div><div class="contact-links"><a class="button" href="https://yandex.ru/maps/org/sm_stomatologiya/45158356463/" target="_blank" rel="noopener noreferrer">Яндекс Карты</a><a class="button outline" href="https://2gis.ru/search/${mapQuery}" target="_blank" rel="noopener noreferrer">Открыть в 2ГИС</a></div></div></section></div><section class="section faq-grid"><div><h2>Перед звонком</h2><p style="margin-top:20px">Пара деталей поможет администратору подобрать приём.</p></div><div>${faqList([['Что сказать при записи?','Назовите повод обращения и сообщите, хотите ли записаться к конкретному специалисту. Уточните время и стоимость консультации.'],['Можно ли записать другого человека?','Обсудите это с администратором. Сообщите, для кого нужен приём, и уточните порядок записи.'],['Если планы изменились?','Позвоните заранее, чтобы отменить или перенести приём.']])}</div></section>`,'Контакты',false));
await page('/documents/','Документы и сведения','Как запросить сведения о клинике, лицензии, специалистах и условиях оказания услуг.',pageBody('Важная информация.<br>В открытом диалоге.','Документы и условия оказания помощи можно запросить у администратора клиники перед визитом.',`<div class="split"><article class="article"><h2>Что можно уточнить</h2>${faqList([['Лицензия и сведения о медицинской организации','Запросите актуальные реквизиты медицинской организации и сведения о лицензии. Электронная копия лицензии на этой странице пока не размещена.'],['Сведения о специалистах','Уточните специальность выбранного врача, образование, действующую аккредитацию и расписание приёма.'],['Прайс и условия оказания платных услуг','Терапевтический и ортопедический прейскуранты доступны на странице стоимости. Порядок заключения договора и условия оплаты уточните в клинике. Согласуйте состав плана лечения до его начала.'],['Правила приёма и обращения пациентов','Уточните порядок записи, переноса приёма и обращения к руководству клиники. Администратор подскажет доступный способ связи.']])}<div class="callout">За актуальными версиями документов обращайтесь в клинику: +7 (831) 270-82-20.</div></article>${aside('Запросить сведения','Администратор подскажет, как ознакомиться с документами и получить ответ на ваш вопрос.','Запрос документов')}</div>`,'Информация о клинике'));
await page('/privacy/','Конфиденциальность','Как используются настройки просмотра и способы связи на сайте СМ-Стоматологии.',pageBody('Конфиденциальность','Информация о настройках сайта и способах связи.',`<article class="article"><h2>Настройки просмотра</h2><p>Выбор увеличенного текста сохраняется в браузере на вашем устройстве. Вернуться к обычному размеру можно кнопкой в верхней части страницы. Эта настройка не отправляется в клинику.</p><h2>Список подготовки</h2><p>Отметки в списке перед визитом действуют только на открытой странице. После перезагрузки они сбрасываются. Список не передаётся администратору.</p><h2>Запись на приём</h2><p>Форма позволяет указать имя, телефон и желаемые дату и время. По вашему согласию предварительная заявка сохраняется только в этом браузере, без отправки в клинику. Это не подтверждённая запись: для согласования приёма позвоните администратору. Данные доступны другим пользователям этого устройства. Просмотреть, скачать или удалить заявки можно в разделе «Заявки на этом устройстве» внутри формы. Они хранятся до удаления вами или очистки данных браузера. Скачанная копия содержит имя и телефон; удаление из браузера не удаляет этот файл. На другом устройстве заявки не появятся. Свободное время пока не проверяется и не блокируется.</p><h2>Внешние ссылки</h2><p>На странице контактов встроена Яндекс Карта. При её загрузке браузер обращается к серверам Яндекса; сервис может обрабатывать технические данные по своим правилам. Почтовое приложение и справочные материалы открываются по вашему выбору. Хостинг может обрабатывать технические сведения, необходимые для показа сайта и управления доступом.</p><h2>Вопросы об обработке данных в клинике</h2><p>Актуальную политику медицинской организации и сведения об обработке данных при записи и лечении запросите у администратора по телефону +7 (831) 270-82-20. Эта страница описывает функции сайта и не заменяет документы клиники.</p></article>`,'О сайте',false));
await page('/tooth/','Структура зуба','Интерактивная схема строения зуба: эмаль, дентин, пульпа и цемент корня. Прокручивайте страницу, чтобы рассмотреть каждый слой.',anatomyPage);
await page('404','Страница не найдена','Запрошенная страница не найдена.',`<div class="container notfound"><div class="eyebrow" style="justify-content:center">404 / Страница не найдена</div><h1>Кажется, вы<br>свернули не туда.</h1><p>Вернитесь на главную или выберите интересующую услугу.</p><a class="button" href="/">На главную</a> <a class="button outline" href="/services/">К услугам</a></div>`);
await writeFile(path.join(out,'robots.txt'),'User-agent: *\nDisallow: /\n');
console.log('Built 20 content pages plus 404.');
